### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by alihadian** [wangziqi2016/index-microbench#2]
I get an error when I run the script.

I put these two lines in `workload_config.inp`:
```
workloade
randint
```

But then when I run make generate_workload
I get the following error:

```
$ make generate_workload
python gen_workload.py workload_config.inp
workload = workloade
key type = randint
sh: workloads/ycsb_load_randint_workloade: No such file or directory
sh: workloads/ycsb_txn_randint_workloade: No such file or directory
Traceback (most recent call last):
  File "gen_workload.py", line 65, in <module>
    f_load = open (out_ycsb_load, 'r')
IOError: [Errno 2] No such file or directory: 'workloads/ycsb_load_randint_workloade'
make: *** [generate_workload] Error 1
```

How should I generate the` workloads/ycsb_*` files that the script is asking for?

**Comment by rohansuri** [comment]
Just self-create the workloads directory for the ycsb binary to generate the workloads into.

`mkdir workloads`

**Comment by alihadian** [comment]
> Just self-create the workloads directory for the ycsb binary to generate the workloads into.
> 
> `mkdir workloads`
Thanks :-)
